// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Use the web configuration
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ-0Fwee9hqlmPb8vAh0bTWw17u3ro0DY',
    appId: '1:663498878910:android:30afaf6f9cd8662aeb13ef',
    messagingSenderId: '663498878910',
    projectId: 'minimalchat-59c8a',
    storageBucket: 'minimalchat-59c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9zrCIaVCMc8C2BPKxk5qaNRas4KznZrw',
    appId: '1:663498878910:ios:c8580020e707d1c1eb13ef',
    messagingSenderId: '663498878910',
    projectId: 'minimalchat-59c8a',
    storageBucket: 'minimalchat-59c8a.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  // Added Firebase web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAyGLGWspqQnwm3JCyk1FS8p_NU7AkSd1g",
    authDomain: "minimalchat-59c8a.firebaseapp.com",
    projectId: "minimalchat-59c8a",
    storageBucket: "minimalchat-59c8a.firebasestorage.app",
    messagingSenderId: "663498878910",
    appId: "1:663498878910:web:d4d27ff491ea66d6eb13ef",
  );
}
